### ISSUE TITLE
hier steht noch ffnord

### ISSUE THREAD

**Issue by rubo77** [Tarnatos/ffki-puppet-config#1]
https://github.com/Tarnatos/ffki-puppet-config/blob/dc3e395660a78c4741bea509ca9cb15a228645e5/steps.txt#L90

ausserdem wollen wir in kiel ja gar kein null crypto erlauben.  (Der Block ist wahrscheinlich aus ffnord kopiert worden, oder?)

**Comment by Tarnatos** [comment]
fixed.

ich möchte schon auf meinen Routern null crypto machen können

**Comment by rubo77** [comment]
müssen wir mal besprechen im NOC, könnten wir ja so beschliessen.
